@startuml

entity "user" {
  email
  password
  admin
  post
  tel
  address
}

entity "cash_on_deliver" {
  price
  more_than
}

entity "cash_on_deliver_term" {
  began_at
}

entity "deliver_price" {
  price
  fee
  began_at
}

entity "tax" {
  rate
  began_at
}

entity "cart" {
}

entity "cart_product" {
  quantity
}

entity "order" {
  deliver_time
  deliver_date
  post
  tel
  address
  cash_on_deliver
  deliver_price
  tax_price
  total
}

entity "order_detail" {
  price
  quantity
}

entity "product" {
  name
  image
  price
  description
  published
  position
}

cash_on_deliver_term--{cash_on_deliver
tax--{order
cart--{cart_product
deliver_price--{order
product--{cart_product
cash_on_deliver--{order
user--{order
order--{order_detail
product--{order_detail

@enduml
