@startuml

entity "user" {
  email
  password
  admin
  name
  post
  tel
  address
}

entity "cash_on_delivery_detail" {
  price
  more_than
}

entity "cash_on_delivery" {
}

entity "delivery_price" {
  price
  per
}

entity "tax" {
  rate
}

entity "cart" {
}

entity "cart_product" {
  quantity
}

entity "order" {
  deliver_time
  deliver_date
  post
  tel
  address
  cash_on_delivery
  delivery_price
  tax_price
  total_without_tax
  total_with_tax
}

entity "order_detail" {
  price
  quantity
}

entity "product" {
  name
  image
  price
  description
  published
  position
}

cash_on_delivery--{cash_on_delivery_detail
tax--{order
cart--{cart_product
delivery_price--{order
product--{cart_product
cash_on_delivery--{order
user--{order
order--{order_detail
product--{order_detail

@enduml
